## Header

In [1]:
import pandas as pd
import requests
import other.keys as keys

In [3]:


headers = {
	"X-RapidAPI-Key": keys.key,
	"X-RapidAPI-Host": "sofasport.p.rapidapi.com"
}

### Player Statistics Result

In [4]:
url_player_statistics_results = "https://sofasport.p.rapidapi.com/v1/teams/player-statistics/result"
querystring_player_statistics_results = {"season_id":"48982","unique_tournament_id":"325","team_id":"5926"}
response_player_statistics_results = requests.get(url_player_statistics_results, headers=headers, params=querystring_player_statistics_results)

In [5]:
json_player_statistics_results = response_player_statistics_results.json()['data']

In [6]:
json_player_statistics_rtgs_results = json_player_statistics_results['rating']

In [7]:
df_rating_results = pd.DataFrame(json_player_statistics_rtgs_results)
df_rating_results.head()

,statistics,playedEnough,player
0,"{'rating': 7.4, 'id': 1104945, 'type': 'overal...",False,"{'name': 'Caíque', 'slug': 'caique', 'shortNam..."
1,"{'rating': 7.3272727272727, 'id': 997987, 'typ...",True,"{'name': 'Luis Suárez', 'slug': 'luis-suarez',..."
2,"{'rating': 7.0789473684211, 'id': 997979, 'typ...",True,"{'name': 'Bitello', 'slug': 'bitello', 'shortN..."
3,"{'rating': 7.0382352941176, 'id': 997977, 'typ...",True,"{'name': 'Franco Cristaldo', 'slug': 'franco-c..."
4,"{'rating': 6.9966666666667, 'id': 1005833, 'ty...",True,"{'name': 'Reinaldo', 'slug': 'reinaldo', 'shor..."

In [8]:
df_rating_player_results = pd.json_normalize(df_rating_results[['playedEnough','player']].to_dict('list'), ['player']).unstack().apply(pd.Series)
df_rating_statistics_results = pd.json_normalize(df_rating_results[['playedEnough','statistics']].to_dict('list'), ['statistics']).unstack().apply(pd.Series)

In [171]:
df_rating_statistics_results.to_clipboard()

In [172]:
df_rating_player_results.to_clipboard()

### Player Statistics

In [9]:
url_player_statistics = "https://sofasport.p.rapidapi.com/v1/events/player-statistics"
querystring_player_statistics = {"event_id":"11067585","player_id":"249647"}
response_player_statistics = requests.get(url_player_statistics, headers=headers, params=querystring_player_statistics)

In [10]:
json_data_players_statistics = response_player_statistics.json()

In [11]:
json_data_players_statistics

{'data': {'player': {'name': 'Walter Kannemann',
   'slug': 'walter-kannemann',
   'shortName': 'W. Kannemann',
   'position': 'D',
   'jerseyNumber': '4',
   'userCount': 1226,
   'id': 249647,
   'marketValueCurrency': 'EUR',
   'dateOfBirthTimestamp': 668908800},
  'team': {'name': 'Grêmio',
   'slug': 'gremio',
   'shortName': 'Grêmio',
   'gender': 'M',
   'sport': {'name': 'Football', 'slug': 'football', 'id': 1},
   'userCount': 214032,
   'nameCode': 'GPA',
   'disabled': True,
   'national': False,
   'type': 0,
   'id': 5926,
   'teamColors': {'primary': '#3399ff',
    'secondary': '#000033',
    'text': '#000033'},
   'fieldTranslations': {'nameTranslation': {'ru': 'Гремио'},
    'shortNameTranslation': {}}},
  'statistics': {'totalPass': 48,
   'accuratePass': 16,
   'totalLongBalls': 6,
   'aerialLost': 0,
   'aerialWon': 0,
   'duelLost': 4,
   'duelWon': 2,
   'challengeLost': 0,
   'totalClearance': 0,
   'outfielderBlock': 0,
   'interceptionWon': 0,
   'totalTackle': 6,
   'wasFouled': 2,
   'fouls': 0,
   'minutesPlayed': 140,
   'touches': 26,
   'rating': 8.46,
   'possessionLostCtrl': 8,
   'expectedGoals': 0,
   'keyPass': 0,
   'ratingVersions': {'original': 7.5, 'alternative': 7.5}},
  'position': 'D'}}

In [12]:
df_players_statistics = pd.DataFrame(json_data_players_statistics['data'])

In [13]:
df_players_statistics

,player,team,statistics,position
name,Walter Kannemann,Grêmio,NaN,D
slug,walter-kannemann,gremio,NaN,D
shortName,W. Kannemann,Grêmio,NaN,D
position,D,NaN,NaN,D
jerseyNumber,4,NaN,NaN,D
userCount,1226,214032,NaN,D
id,249647,5926,NaN,D
marketValueCurrency,EUR,NaN,NaN,D
dateOfBirthTimestamp,668908800,NaN,NaN,D
gender,NaN,M,NaN,D
sport,NaN,"{'name': 'Football', 'slug': 'football', 'id': 1}",NaN,D
nameCode,NaN,GPA,NaN,D
disabled,NaN,True,NaN,D
national,NaN,False,NaN,D
type,NaN,0,NaN,D
teamColors,NaN,"{'primary': '#3399ff', 'secondary': '#000033',...",NaN,D
fieldTranslations,NaN,"{'nameTranslation': {'ru': 'Гремио'}, 'shortNa...",NaN,D
totalPass,NaN,NaN,48,D
accuratePass,NaN,NaN,16,D
totalLongBalls,NaN,NaN,6,D
aerialLost,NaN,NaN,0,D
aerialWon,NaN,NaN,0,D
duelLost,NaN,NaN,4,D
duelWon,NaN,NaN,2,D
challengeLost,NaN,NaN,0,D
totalClearance,NaN,NaN,0,D
outfielderBlock,NaN,NaN,0,D
interceptionWon,NaN,NaN,0,D
totalTackle,NaN,NaN,6,D
wasFouled,NaN,NaN,2,D
fouls,NaN,NaN,0,D
minutesPlayed,NaN,NaN,140,D
touches,NaN,NaN,26,D
rating,NaN,NaN,8.46,D
possessionLostCtrl,NaN,NaN,8,D
expectedGoals,NaN,NaN,0,D
keyPass,NaN,NaN,0,D
ratingVersions,NaN,NaN,"{'original': 7.5, 'alternative': 7.5}",D

### Events

In [44]:
url = "https://sofasport.p.rapidapi.com/v1/players/events"
querystring = {"page":"0","player_id":"558820","course_events":"last"}

response_players = requests.get(url, headers=headers, params=querystring)

In [45]:
json_data_players = response_players.json()

In [51]:
df = pd.DataFrame(json_data_players['data']['events'])

In [65]:
df.head(2)

,tournament,roundInfo,customId,status,winnerCode,homeTeam,awayTeam,homeScore,awayScore,time,...,id,startTimestamp,slug,finalResultOnly,aggregatedWinnerCode,hasEventPlayerHeatMap,awayRedCards,previousLegEventId,homeRedCards,hasXg
0,"{'name': 'Gaúcho', 'slug': 'gaucho', 'category...",{'round': 9},BtcsBhRd,"{'code': 100, 'description': 'Ended', 'type': ...",1,"{'name': 'Grêmio', 'slug': 'gremio', 'shortNam...","{'name': 'Novo Hamburgo', 'slug': 'novo-hambur...","{'current': 6, 'display': 6, 'period1': 5, 'pe...","{'current': 1, 'display': 1, 'period1': 0, 'pe...",{'currentPeriodStartTimestamp': 1677286050},...,10912646,1677279600,gremio-novo-hamburgo,False,NaN,NaN,NaN,NaN,NaN,NaN
1,"{'name': 'Copa do Brasil', 'slug': 'copa-do-br...","{'round': 1, 'name': 'Round 1', 'slug': 'round...",BtcskFn,"{'code': 100, 'description': 'Ended', 'type': ...",2,"{'name': 'Campinense', 'slug': 'campinense', '...","{'name': 'Grêmio', 'slug': 'gremio', 'shortNam...","{'current': 0, 'display': 0, 'period1': 0, 'pe...","{'current': 2, 'display': 2, 'period1': 1, 'pe...","{'injuryTime1': 2, 'injuryTime2': 4, 'currentP...",...,11055706,1677711600,gremio-campinense,False,2.0,True,NaN,NaN,NaN,NaN

In [70]:
df.to_clipboard()

### Events Statistics

In [113]:
url_event_data = "https://sofasport.p.rapidapi.com/v1/events/statistics"
querystring_event_data = {"event_id":"11067394"}
response_event_data = requests.get(url_event_data, headers=headers, params=querystring_event_data)

In [114]:
json_data_event_data = response_event_data.json()

In [126]:
df_event_data = pd.DataFrame(json_data_event_data['data'])
df_event_data

  period                                             groups
0    ALL  [{'groupName': 'Expected', 'statisticsItems': ...
1    1ST  [{'groupName': 'Expected', 'statisticsItems': ...
2    2ND  [{'groupName': 'Expected', 'statisticsItems': ...

In [143]:
df_event_data_groups = pd.json_normalize(df_event_data.to_dict('list'), ['groups']).unstack().apply(pd.Series)
df_event_data_groups_stats = pd.json_normalize(df_event_data_groups.to_dict('list'), ['statisticsItems']).unstack().apply(pd.Series)

In [144]:
df_event_data_groups_stats.to_clipboard()

### Players Data

In [107]:
url_players_data = "https://sofasport.p.rapidapi.com/v1/players/data"
querystrin_players_data = {"player_id":"558820"}
response_players_data = requests.get(url_players_data, headers=headers, params=querystrin_players_data)

In [146]:
response_players_data.json()['data']
df_player_data = pd.DataFrame(response_players_data.json()['data'])
df_player_data.head(2)

,name,firstName,lastName,slug,shortName,team,position,jerseyNumber,height,preferredFoot,retired,userCount,id,country,shirtNumber,dateOfBirthTimestamp,contractUntilTimestamp,proposedMarketValue,proposedMarketValueRaw
name,Franco Cristaldo,,,franco-cristaldo,Franco Cristaldo,Grêmio,M,19,175,Right,False,1046,558820,Argentina,19,840067200,1798675200,7200000,NaN
slug,Franco Cristaldo,,,franco-cristaldo,Franco Cristaldo,gremio,M,19,175,Right,False,1046,558820,NaN,19,840067200,1798675200,7200000,NaN

###  Player Events

In [145]:
url_players_events = "https://sofasport.p.rapidapi.com/v1/players/events"
querystring_players_events = {"page":"0","player_id":"558820","course_events":"last"}
response_players_events = requests.get(url_players_events, headers=headers, params=querystring_players_events)

In [150]:
df_player_data_events = pd.DataFrame(response_players_events.json())

In [151]:
df_player_data_events

                                                               data
events            [{'tournament': {'name': 'Gaúcho', 'slug': 'ga...
hasNextPage                                                    True
incidentsMap      {'10912629': {'goals': 1}, '10912646': {'goals...
onBenchMap                     {'11067500': True, '11256867': True}
playedForTeamMap  {'10912629': 5926, '10912646': 5926, '11055706...
statisticsMap     {'11055706': {'rating': 7.6}, '11103583': {'ra...

In [162]:
df_player_data_events_events = pd.DataFrame(df_player_data_events.iloc[0]['data'])
df_player_data_events_events.to_clipboard()

In [164]:
df_player_data_events_incidentsMap = pd.DataFrame(df_player_data_events.iloc[2]['data'])
df_player_data_events_incidentsMap.to_clipboard()

In [165]:
df_player_data_events_statisticsMap = pd.DataFrame(df_player_data_events.iloc[5]['data'])
df_player_data_events_statisticsMap.to_clipboard()